pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'hemakumariperumandla/devops-metrics:latest'
    }
    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE -f app/Dockerfile .'
            }
        }
        stage('Push Docker Image to Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub', url: '']) {
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f jenkins/k8s/flask-deployment.yaml'
            }
        }
    }
}
