pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'your-dockerhub-username/devops-metrics:latest'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git credentialsId: 'github-ssh', url: 'https://github.com/perumandlahemakumari/devops-metrics.git', branch: 'main'
            }
        }
        stage('Build & Test') {
            steps {
                sh 'pip install -r requirements.txt'
                sh 'pytest'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }
        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub', url: '']) {
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/flask-deployment.yaml'
            }
        }
    }
}
